stages:
- name: test
  steps:
  - runScriptConfig:
      image: php:latest
      shellScript: |-
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
        composer install
        ./vendor/bin/phpunit
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
