stages:
- name: test
  steps:
  - runScriptConfig:
      image: composer
      shellScript: |-
        composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
        composer install -vvv
        ./vendor/bin/phpunit
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
