stages:
- name: test
  steps:
  - runScriptConfig:
      image: php:7.2-cli
      shellScript: |-
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
        composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
        composer install
        ./vendor/bin/phpunit
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
