version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: jianyl/php-7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - "8890:8080"