version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: jianyl/php-7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - "8890:8080"
    slim-production:
        image: jianyl/nginx-php-fpm
        working_dir: /var/www/html
        environment:
            WEBROOT: /var/www/html/public
        ports:
            - 8090:80
        volumes:
            - .:/var/www/html
            - logs:/var/www/html/logs
            - ./config-nginx.d/:/etc/nginx/sites-enabled/
