database:
    driver: pgsql
    host: postgres
    port: 5432
    database: demo
    username: postgres
    password: 12345678
    charset: utf8
    prefix:
    schema: public
    sslmode: prefer

    #driver: mysql
    #host:
    #port: 3306
    #database:
    #username:
    #password:
    #charset: utf8
    #collation: utf8_unicode_ci
    #prefix: ''
    #strict: true
    #engine: null
doctrine:
    connection:
        driver: pdo_pgsql
        host: postgres
        port: 5432
        dbname: demo
        user: postgres
        password: 12345678
        charset: utf-8
redis:
    host: redis
    password:
socialite:
    wechat:
        app_id:
        secret:
        response_type: array
        log:
            level: debug
            file: